### ISSUE TITLE
error while reading D1SUNED v4.1.2 meshtal file

### ISSUE THREAD

**Issue by dodu94** [Fusion4Energy/F4Enix#37]
It is unclear if it is an issue specifically of D1SUNED v4.1.2 or simply that the header of this file generates a bug. To be fixed. simple example in attachment.
[meshtal.txt](https://github.com/Radiation-Transport/F4Enix/files/13374366/meshtal.txt)

**Comment by dodu94** [comment]
Until fix, the workaround is simply to modify the header of file (description of the header input, first 1-2 lines)

**Comment by AlvaroCubi** [comment]
This problem also appears in the D1SUNED v4.1.1.
