### ISSUE TITLE
[Feature request] - GVR function improvement

### ISSUE THREAD

**Issue by Radiation-Transport** [Fusion4Energy/F4Enix#59]
**Is your feature request related to a problem? Please describe.**
User cannot change the maximum split ratio and the softening without changing the function.

**Describe the solution you'd like**
Add the possibility to the user to change the maximum split ratio and the softening.
Beta and softening should be 5 and 1 by default. Moreover improve the documentation so the user can understand how to use it properly.

**Describe alternatives you've considered**
Leave as it is.

**Additional context**

**Comment by AlvaroCubi** [comment]
To clarify: the user can already change the maximum splitting ration and the default value is already 5. The softening is not yet applied by default, I will implement it and solve the issue.
