### ISSUE TITLE
[BUG] - readMesh method fails for cartesian CuV meshes when used more than once in a row

### ISSUE THREAD

**Issue by AlbertoBittes** [Fusion4Energy/F4Enix#62]
**Describe the bug**
Cartesian CuV FMESH tallies are read incorrectly by readMesh method if read multiple times. The bins are put in place of the geometrical bounds. The result is that the mesh is not positioned correctly in space.

**To Reproduce**
1. Read a meshtal file by initializing a Meshtal() object
2. use readMesh method with whatever mesh
3. use readMesh method again to read the same previous mesh

**Expected behavior**
Correct assigning of the bounds of the mesh. Temporary solution: re-read Meshtal file before re-reading mesh (heavily time consuming for large files)

**Screenshots**
This part of the code seems to be the responsible of the bad behavior.
![image](https://github.com/Fusion4Energy/F4Enix/assets/119672385/584fc566-c407-4812-922b-1c7fffd66736)

**Desktop (please complete the following information):**
 - OS: Windows
 - F4Enix version: last
 - Python version 3.10.13

**Comment by dodu94** [comment]
Thanks for this Alberto. Most likely, a faster workaround is to copy the Meshtal object before reading fmeshes instead of re-reading the Meshtal itself.

**Comment by AlbertoBittes** [comment]
Yes, I would leave this as it is for the moment, just documenting it I think is enough.
