### ISSUE TITLE
[BUG] - Notebooks raise raise ValueError due to empty mesh

### ISSUE THREAD

**Issue by shimwell** [Fusion4Energy/F4Enix#72]
**Describe the bug**
While adding tests to run all the notebooks I noticed that the existing stable branch has a error when running the notebooks and it is actually on the docs as well so easy to see [here](https://f4enix.readthedocs.io/en/stable/examples/output/jupyters/meshtal.html) but I include a screenshot 
![Screenshot 2024-06-06 132927](https://github.com/Fusion4Energy/F4Enix/assets/8583900/f5304c2e-9e23-41fa-b28a-9423bf96fe4e)

**To Reproduce**
for example:
1. checkout the current developing or main branch
2. run this notebook ```docs/source/examples/output/jupyters/meshtal.ipynb```
3. See error on the 2nd from last cell

**Expected behavior**
notebook should run without error

**Desktop (please complete the following information):**
 - OS: WSL, ubuntu CI
 - F4Enix version developing
 - Python version 3.11

**Comment by dodu94** [comment]
It seems to work with pyvista v0.42.x and not v0.43.x, to be further investigated
