### ISSUE TITLE
[BUG] - creating a Material fails with Typeerror

### ISSUE THREAD

**Issue by shimwell** [Fusion4Energy/F4Enix#76]
**Describe the bug**
Trying to make a F4enix material like this

```
import f4enix
f4enix_material = Material(zaids=[(3007, -0.1), (3006, -0.9)], elem='Li', name='mat1')
```

results in this error message
```
  File "/home/j/miniforge3/envs/f4enix_dev/lib/python3.11/site-packages/f4enix/input/materials.py", line 727, in __init__
    submat = submaterials[0]
             ~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

```

**To Reproduce**
run the above code, hopefully I've understood the material class correctly

**Expected behavior**
I was expecting to met a material object returned

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux
 - F4Enix version dev
 - Python version 3.11

**Comment by dodu94** [comment]
Hello Jonathan, from the doc:
![image](https://github.com/Fusion4Energy/F4Enix/assets/25747626/2a892220-6e4d-48a7-b337-6c5e70aa8f4f)
So either you express it with a natural zaid notation (1000) if you want elements, or specific zaids (1001). Do not touch the elements attribute and use mcnp naming convention for materials (like M1).

**Comment by dodu94** [comment]
Yeah creating a material from the __init__ is not straightforward due to historical reason. There are a bunch of class constructor method though  if you check the doc I am using the ``Material.from_zaids()`` method and not the __init__
