### ISSUE TITLE
[DOC] - ww module documentation to be extended

### ISSUE THREAD

**Issue by Radiation-Transport** [Fusion4Energy/F4Enix#92]
# What where you looking for
WW module documentation is scarse and does not include the one previously present in https://github.com/Radiation-Transport/iWW-GVR/blob/master/docs/memorandum_-_iWW-GVR_2JFFDN_v1_1.pdf.

# Is the information available in the doc but not where you would expect?
No, it is only available in deprecated repository https://github.com/Radiation-Transport/iWW-GVR/blob/master/docs/memorandum_-_iWW-GVR_2JFFDN_v1_1.pdf.

# Is information completely lacking or partial?
It is partial.

# Where would you insert the missing information?
https://f4enix.readthedocs.io/en/stable/examples/input/jupyters/ww.html

**Comment by AlvaroCubi** [comment]
Addressed in 36b66db21f8bcd5cee8d7a8d46052f8a59650863
